# Generated by Django 5.0.1 on 2024-01-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блока')),
                ('description', models.TextField(verbose_name='Описание блока')),
                ('image', models.ImageField(upload_to='themes/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_word', models.CharField(db_index=True, max_length=150, verbose_name='russian words')),
                ('eng_word', models.CharField(db_index=True, max_length=150, verbose_name='english words')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulare.themeblock')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
    ]
